### ISSUE TITLE
styling LecturePage

### ISSUE THREAD

**Issue by mateusz-stempniewicz** [akai-org/wydzialowe-gwiazdki#23]

**Comment by mateusz-stempniewicz** [comment]
@biniox chciałbym, żebyś do lecturePage jeszcze dorobił:
- [x] komponent LectureSection, który będzie przyjmował w propsach tytuł + listę wykładowców do wygenerowania. Będzie on posiadał metodę do mapowania wykładowców na componenty LectureComponent
- [x] w komponencie LectureContainer żebyś stworzył metodę getLectures(lectureType) przyjmującą jako parametr typ prowadzonych zajęć, która będzie dla konkretnego Id przedmiotu zwracała listę prowadzących, np. żeby otrzymać listę ćwiczeniowców powinniśmy ją wywołać w następujący sposób this.getLectures('exercises')
- [x] w komponencie LectureContainer dodaj 3 razy LectureSection (dla "Wykładowców", "Ćwiczeniowców", "Laborantów")
- [x] spróbuj ostylować wszystko mniej więcej w taki sposób jak na załączonych screenach
![screenshot 1](https://user-images.githubusercontent.com/5738391/47863613-f1e86500-ddf7-11e8-827d-d31f72b519fb.png)
![screenshot 2](https://user-images.githubusercontent.com/5738391/47863622-f7de4600-ddf7-11e8-9949-97f7358efa60.png)

- [x] dodaj jeszcze hover na classie LectureComponents, żeby po najechaniu zmnieniła background-color na rgba(192,192,192,0.05)
- [x] dodaj hover na gwiazdkach, żeby zmieniły kolor na przydymiony żółty
- [x] jeśli jest więcej niż jedna osoba prowadząca dany przedmiot daj między nimi border-bottom: 1px solid rgba(192,192,192,0.25); ostatnia osoba nie ma takiego border (patrz screen 1)

**Comment by biniox** [comment]
Ok, zrobione

**Comment by mateusz-stempniewicz** [comment]
@biniox to stwórz nowego pull requesta
