### ISSUE TITLE
Strona rejestracji

### ISSUE THREAD

**Issue by mateusz-stempniewicz** [akai-org/wydzialowe-gwiazdki#37]
- [ ] url '/register'
- [x] design
- [ ] powrót do strony logowania
- [ ] formularz rejestracji
- [ ] walidacja formularza
  - [ ] pola wymagane: email (będzie używany jako login), hasło, powtórz hasło
  - [ ] email jest już wykorzystywany
- [ ] przycisk zarejestruj
- [ ] po rejestracji automatyczne zalogowanie do aplikacji

**Comment by Magdalena97** [comment]
osoby tylko z email politechniki moga sie zarejestrowac + wydzial jako pole do rejestacji w postaci select
